### ISSUE TITLE
Submit to halite.io

### ISSUE THREAD

**Issue by seb-odessa** [mjhanninen/umpteenth-anion#1]
Hi
Did you was able to submit your bot to halite.io?

I can't understand how to do it.

Thanks, Pavel

**Comment by mjhanninen** [comment]
Hi Pavel

Yes, this Works for Me! (tm) well. To give some background I'm working on OS X (or macOS) and I have installed Rust via [rustup](https://www.rustup.rs) and other development tools via [Homebrew](http://brew.sh).

To submit a bot I first build the .zip file (named `dist/pod.zip`) on the command line:

``` .sh
$ cd path/to/halite-soija
$ bin/mkpod.sh
```

Having built the .zip file I open [Halite homepage](https://halite.io/) in my browser, select **Submit** from the tab, pick the file `path/to/halite-soija/dist/pod.zip`, and finally send it. That's all there is to it. 

If you're working on Linux the scripts should work as-is or, at most, with minor adjustments. If you're working on Windows, I'm afraid you're on your own. You would need to package the .zip file by hand and include the `Cargo.toml` file and the `src/` directory (preserving the directory structure) in it.

I hope that helps!

**Comment by seb-odessa** [comment]
Thank you for response.
It was some kind of error, I suppose.
I have recreated the zip and all works fine now.

Thanks, Pavel.
